---
- hosts: all
  become: yes
  tasks:
    - name: apt update & apt upgrade
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
        autoclean: yes
    - name: Reboot All Hosts
      reboot:
