---
- hosts: all
  become: yes
  tasks:
    - name: Disable Root Authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin no"
    - name: Enable Public Key Authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#?PubkeyAuthentication"
        line: "PubkeyAuthentication yes"
    - name: Disable Password Authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"
    - name: Disable Empty Password Login
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#?PermitEmptyPasswords"
        line: "PermitEmptyPasswords no"
