---
- name: Ensure overlay networks exist
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: overlay
    attachable: true
    internal: "{{ item.internal | default(false) }}"
    scope: swarm
    driver_options: "{{ {'encrypted': 'true'} if item.encrypted | default(false) else omit }}"
    state: present
  loop: "{{ set_docker_network_overlay }}"
  when: set_docker_network_overlay | length > 0
  delegate_to: "{{ groups['swarm_managers'] | first }}"
  run_once: true
