---
- name: Configure SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "^#?Port", line: "Port {{ ssh_port }}" }
    - { regexp: "^#?PermitRootLogin", line: "PermitRootLogin {{ ssh_permit_root_login }}" }
    - { regexp: "^#?PubkeyAuthentication", line: "PubkeyAuthentication {{ ssh_pubkey_authentication }}" }
    - { regexp: "^#?PasswordAuthentication", line: "PasswordAuthentication {{ ssh_password_authentication }}" }
    - { regexp: "^#?PermitEmptyPasswords", line: "PermitEmptyPasswords {{ ssh_permit_empty_passwords }}" }
  notify: restart ssh
