limit_req_zone $binary_remote_addr zone=req_limit_per_ip:10m rate=2r/s;
limit_conn_zone $binary_remote_addr zone=conn_limit_per_ip:10m;

  server {
    listen 80;
    server_name YourDomain;
    access_log /var/log/nginx/YourDomain-access.log;
    error_log /var/log/nginx/YourDomain-error.log;

    return 301 https://$host$request_uri;
  }
  
  server {
    listen 443 ssl;
    server_name YourDomain;

    ssl_certificate /etc/letsencrypt/live/YourDomain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/YourDomain/privkey.pem;

    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Frame-Options "SAMEORIGIN";
    add_header Referrer-Policy "no-referrer-when-downgrade";

    location / {
      proxy_pass http://localhost:8080;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      limit_req zone=req_limit_per_ip burst=5 nodelay;
      limit_conn conn_limit_per_ip 30;
    }
  }
