driftfile /var/lib/ntp/ntp.drift
leapfile /usr/share/zoneinfo/leap-seconds.list

statistics loopstats peerstats clockstats
filegen loopstats file loopstats type day enable
filegen peerstats file peerstats type day enable
filegen clockstats file clockstats type day enable

pool time.cloudflare.com

restrict default kod limited nomodify nopeer noquery notrap
restrict 127.0.0.1
restrict ::1

restrict source notrap nomodify noquery