---
name: Ansible Configuration Check

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  ansible-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible passlib ansible-lint yamllint
          pip install --upgrade ansible-lint

      - name: Check YAML syntax with yamllint
        run: |
          yamllint .

      - name: Check Ansible syntax
        run: |
          ansible-playbook --syntax-check playbook.yml

      - name: Run ansible-lint
        run: |
          ansible-lint .
